### PR TITLE
Remove the IAM Policy Controller

### PR DESCRIPTION
**Pull request by yiraeChristineKim**
Delete iam-policy-controller trace in this repo
Ref: https://issues.redhat.com/browse/ACM-10859

### CODE REVIEW

**Comment by dhaiducek** [comment]
How is this PR different from the sync one?
- #687

**Comment by dhaiducek** [comment]
I think you might just need to re-run the CI in the sync PR. 🙂

**Comment by dhaiducek** [comment]
> I don't know. Why it doesn't work?

It was probably a flake--you can probably just retry it?

**Comment by yiraeChristineKim** [comment]
> > I don't know. Why it doesn't work?
> 
> It was probably a flake--you can probably just retry it?

I cherry-picked.. no conflicts.. How to rerun mirroring?

**Comment by dhaiducek** [comment]
> I cherry-picked.. no conflicts.. How to rerun mirroring?

Sorry, I meant the CI in the PR failed, not that the mirroring failed:
image
I've re-run the failed workflow, and it's running right now: https://github.com/stolostron/governance-policy-propagator/pull/686

**Pull request closed without merging**
