### PR TITLE
Add the policy-encryption-keys controller

### PR DESCRIPTION
**Pull request by mprahl**
This controller is responsible for rotating encryption keys in the
policy-encryption-key secrets for each managed cluster.

This adds a watch to such secrets, which inherently caches these values
so the custom encryption key cache for the main controller was removed.

Resolves:
https://github.com/stolostron/backlog/issues/18723

### CODE REVIEW

**Comment by mprahl** [comment]
/unhold confirmed the ACLs are all set from this previous PR:
https://github.com/stolostron/grc-chart/pull/66

**Review by dhaiducek — APPROVED** [review]
LGTM! Good work, @mprahl!

**Pull request merged**
