### PR TITLE
Support policy propagation through policyset

### PR DESCRIPTION
**Pull request by ycao56**
stolostron/backlog#18401
- Added watch on `PolicySet` resources
- Implemented a mapper and predicate for `PolicySet` watch
- Added `PolicySet` to pb.subject.kind enum list
- Added `PolicySet` support to existing mapper and predicate
- Added `PolicySet` field to status.placement

Signed-off-by: Yu Cao <ycao@redhat.com>

### CODE REVIEW

**Comment by dhaiducek** [comment]
I'm a bit confused. What's the difference between this PR and this one?
- #150

**Comment by ycao56** [comment]
> I'm a bit confused. What's the difference between this PR and this one?
> 
>     * [Support policy propagation through policyset #150](https://github.com/stolostron/governance-policy-propagator/pull/150)

I reverted the main as the PR was not ready (forgot to /hold) to merge by force pushing. Intended to leave the `main` branch clean. This PR is same as https://github.com/stolostron/governance-policy-propagator/pull/150 with some modifications.

**Review by willkutler — APPROVED** [review]

**Pull request merged**
